import "dotenv/config";
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import pg from 'pg';

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const students = [
  { fullName: "MUHAMMAD, RAHMA L.", grade: 7 },
  { fullName: "TOMENIO, LIAM ANDRIE D.", grade: 7 },
  { fullName: "CHUA, AUDRIC DANIEL A.", grade: 7 },
  { fullName: "ALIFDEEN, MOHAMMED JAWHAR S.", grade: 8 },
  { fullName: "BAYLEN, RENZ MICHAEL INARSOLIN", grade: 9 },
  { fullName: "HERNANDEZ, ZED REH JR. D.", grade: 10 },
  { fullName: "CABARLOC, MITZUO HIMURA O.", grade: 7 },
  { fullName: "SINGHID, ETHAN MANUEL S.", grade: 11 },
  { fullName: "CABANTOC, AEDAN D.", grade: 8 },
  { fullName: "AQUINO, ERICH KYLIE P.", grade: 10 },
  { fullName: "ALDAVE, MHEL MARIANE R.", grade: 9 },
  { fullName: "GATDULA, YOHANCE AYMON V.", grade: 10 },
  { fullName: "CAYABYAB, ANTOINE MIGUEL M.", grade: 7 },
  { fullName: "AGAPAN, MA. QUEENSLEE L.", grade: 12 },
  { fullName: "MEDENILLA, AVERY JOHN", grade: 7 },
  { fullName: "PUGEDA, ZIAN M.", grade: 8 },
  { fullName: "FRANCISCO, ZEINA V.", grade: 12 },
  { fullName: "DELA PEÑA, GIAN LEE G.", grade: 7 },
  { fullName: "EL MAAKOURI, LOUISE NATHANIEL P.", grade: 9 },
  { fullName: "ARANDID, ASHLEY SHEIN F.", grade: 10 },
  { fullName: "ARANDID, MIKAYLA LEIGH F.", grade: 7 },
  { fullName: "NITURA, KENSHIN M.", grade: 7 },
  { fullName: "WABIE, DOMINIQUE NATHAN C.", grade: 10 },
  { fullName: "TORRES, ARLAN SHANNE T.", grade: 12 },
  { fullName: "ENRILE, ELLRINE DRAKE C.", grade: 7 },
  { fullName: "BAUTISTA, JULIANNE C.", grade: 11 },
  { fullName: "BUTT, AHMED YASIR ARFAT L.", grade: 8 },
  { fullName: "JAZO, KEISHA CHLOE B.", grade: 10 },
  { fullName: "JAZO, KESTER CLYDE B.", grade: 11 },
  { fullName: "PILON, REUBEN L.", grade: 8 },
  { fullName: "VILLONES, CASSEY KARYLE C.", grade: 11 },
  { fullName: "EDUBA, SAMANTHA JASMINE R.", grade: 11 },
  { fullName: "ALARCON, YUNA ALEIGHA D.", grade: 12 },
  { fullName: "PENG, ZHYRUS ETHAN T.", grade: 8 },
  { fullName: "DE VERA, NATHAN ZACHARY A.", grade: 7 },
  { fullName: "VERANO, YAEL EZRA D.", grade: 8 },
  { fullName: "MAGNAYE, HANZEL JAMES", grade: 8 },
  { fullName: "SAYAS, SEBASTIAN B.", grade: 8 },
  { fullName: "MAÑAGO, JAIME ANNE M.", grade: 7 },
  { fullName: "PAULE, CRISS EVERTT S.", grade: 9 },
  { fullName: "DELA PEÑA, MIKEL RUI C.", grade: 7 },
  { fullName: "MAGDAY, LIAM JAMES T.", grade: 7 },
  { fullName: "HERNANDEZ, DANIELLA NICOLE D.", grade: 9 },
  { fullName: "GALLENITO, JANROYCE", grade: 10 },
  { fullName: "LLAMES, PRINCE DARWAINE M.", grade: 10 },
  { fullName: "TOR, FRANCINE JEAN F.", grade: 10 },
  { fullName: "TOR, FRANCIS ROBERT F.", grade: 8 },
  { fullName: "ASUNCION, FRANCESCA JAMIE B.", grade: 10 },
  { fullName: "RODELAS, BRYCE MATTAN KEITH C.", grade: 7 },
  { fullName: "MONTEMAYOR, OLIVER JACOB D.", grade: 8 },
  { fullName: "ITURALDE, RANELEENE MAGDALEENE C.", grade: 7 },
  { fullName: "NIEVA, JEMILAH IZZY M.", grade: 7 },
  { fullName: "MANACSA, EZEKIEL B.", grade: 8 },
  { fullName: "MANACSA, MICAH JOY B.", grade: 9 },
  { fullName: "ALARCON, ZIYHANNE AMBER R.", grade: 7 },
  { fullName: "ORBITA, MATT RAFFAELE V.", grade: 9 },
  { fullName: "LAYSON, JAN GABRIEL V.", grade: 8 },
  { fullName: "AYO, MARCIAL JOMARRY M.", grade: 9 },
  { fullName: "MALLARI, JOHN NAITHAN P.", grade: 7 },
  { fullName: "DAYANGCO, PAUL NORBEL DWIN T.", grade: 8 },
  { fullName: "VILLAR, THAMINA ISABEL A.", grade: 8 },
  { fullName: "TANDOG, RAFA L.", grade: 8 },
  { fullName: "NAVARRO, JAMES G.", grade: 11 },
  { fullName: "BALDOVE, EDRY VON D.", grade: 7 },
  { fullName: "URBANO, AMIRA SHEBA A.", grade: 12 },
  { fullName: "VALMADRID, AVRIA LANA H.", grade: 7 },
  { fullName: "RANTE, KEITH PAOLO M.", grade: 11 },
  { fullName: "TACUSALME, NATHALIE JANE A.", grade: 11 },
  { fullName: "MONDIA, CLAYTON P.", grade: 7 },
  { fullName: "CYRICQK MATTHEW S. TAGULAO", grade: 8 },
  { fullName: "CERES, PRINCESS JANAIRE VIRNALOU S.", grade: 8 },
  { fullName: "TREYES, VENICE DOMINIQUE S.", grade: 7 },
  { fullName: "DELA CRUZ, ADEN DANIEL D.", grade: 8 },
  { fullName: "CAGAMPANG, DESTHAN RAE C.", grade: 7 },
  { fullName: "CAGAMPANG, NATHAN RYLE C.", grade: 8 },
  { fullName: "NEPOMUCENO, ETHAN THOMAS B.", grade: 9 },
  { fullName: "MOJARES, RYLLIE YSABELLE C.", grade: 9 },
  { fullName: "ESTREBO, ANDREA MARRIE V.", grade: 9 },
  { fullName: "MAGBOO, ENRICO JULIAN G.", grade: 12 },
  { fullName: "FOJA, CATALIAH KLENJCZEE V.", grade: 8 },
  { fullName: "QUENIO, LUKE GABRIEL A.", grade: 10 },
  { fullName: "QUENIO, PIERRE JACOB A.", grade: 7 },
  { fullName: "BALTAZAR, AKHIO ZIV ZABDIEL C.", grade: 7 },
  { fullName: "SOLATORIO, RAY AIZEN P.", grade: 9 },
  { fullName: "GUIJO, ZEPHANIAH JAY A.", grade: 8 },
  { fullName: "VISTA, PRINCE MICHAEL D.", grade: 8 },
  { fullName: "VISTA, PRINCESS MITCHEDES D.", grade: 9 },
  { fullName: "MAMAUAG, ADRIEL IZRI A.", grade: 8 },
  { fullName: "PELOTERA, LERKXON G.", grade: 11 },
  { fullName: "PELOTERA, LLERRY ZHINT G.", grade: 7 },
  { fullName: "NARCISO, DUNCAN JOSEPH R.", grade: 7 },
  { fullName: "DOMINGO, JEHN MYRISH C.", grade: 12 },
  { fullName: "RABAYA, RONDELL MIKHAEL ANGELO T.", grade: 9 },
  { fullName: "PASCUA, ELIJAH NATHANIEL C.", grade: 10 },
  { fullName: "CRUZ, KATRINA AMBER A.", grade: 12 },
  { fullName: "PUNSALANG, ZIANNE CRISZETTE S.", grade: 7 },
  { fullName: "QUIZZAGAN, MARIAH BELLA B.", grade: 10 },
  { fullName: "PAULAR, ELLA SOPHIA Y.", grade: 7 },
  { fullName: "OLETE, AERON FRANCIS G.", grade: 7 },
  { fullName: "SERRANO, PAUL CZARR BIEL D.", grade: 8 },
  { fullName: "SAN JOSE, DOMINIC M.", grade: 7 },
  { fullName: "SAN JOSE, MA. CHRISTINA M.", grade: 9 },
  { fullName: "SATURAY, MIHAEL CHLOE T.", grade: 9 },
  { fullName: "DAGUIO, ALEX MATEO L.", grade: 8 },
  { fullName: "BATOMALAQUE, CLIO JULIA N.", grade: 10 },
  { fullName: "RAMOS, JARED Y.", grade: 7 },
  { fullName: "AMURAO, RAVEN JAIRUS A.", grade: 8 },
  { fullName: "FLORES, ELIZABETH JOY I.", grade: 7 },
  { fullName: "GARCIA, JOSE GIL IV M.", grade: 8 },
  { fullName: "DIAZ, RUZZEL ANGEL G.", grade: 11 },
  { fullName: "ESPIRITU, JORGE LEXI D.", grade: 10 },
  { fullName: "BORRES, FRANCIS DWAYNE A.", grade: 10 },
  { fullName: "CASIQUIN, JEANINE ZIAHNELL D.", grade: 12 },
  { fullName: "VILLALUZ, VICENZO SANTINO D.", grade: 11 },
  { fullName: "CABALLERO, ANECAH FATIMA S.", grade: 12 },
  { fullName: "ROTUGAL, JELSHIN REDD L.", grade: 7 },
  { fullName: "ELEGIDO, KIARA LOUISE", grade: 8 },
  { fullName: "MAGO, DARLYN JENRYL R.", grade: 11 },
  { fullName: "ARENAS, ANTHEA A.", grade: 10 },
  { fullName: "CABRAL, QUINN BEATRICE J.", grade: 10 },
  { fullName: "ZARAGOSA, SOFIA CHESKA NICOLE R.", grade: 11 },
  { fullName: "DE CASTRO, ADAM KYLE P.", grade: 9 },
  { fullName: "VILLANUEVA, LIAM ELIEZER P.", grade: 7 },
  { fullName: "GALIDO, MATT GEOFFRY", grade: 12 },
  { fullName: "MODELO, CHRISTIAN CALEB B.", grade: 8 },
  { fullName: "MIRA, ELHYZA KEITH M.", grade: 12 },
  { fullName: "GUTIERREZ, DAPHNETTE DANNES T.", grade: 11 },
  { fullName: "TANGALIN, CAROLAI VENICE J.", grade: 10 },
  { fullName: "GOMORERA, CLARISSA DENISE G.", grade: 8 },
  { fullName: "ESPEDIDO, CLOUD HEI V.", grade: 12 },
  { fullName: "CRUZAT, PATRICK JAMES D.", grade: 12 },
  { fullName: "CRUZAT, DEANNE JACE D.", grade: 8 },
  { fullName: "CLAUDIO, JHANZ JOSE B.", grade: 8 },
  { fullName: "EPINO, BARTOLOME II D.", grade: 7 },
  { fullName: "LIWANAG, BAROM MIGUEL G.", grade: 10 },
  { fullName: "ATOS, FELICITY MARU L.", grade: 9 },
  { fullName: "ARCADIO, KRIZ ANNE S.", grade: 7 },
  { fullName: "SELOSE, MAXENE ISABELLE", grade: 9 },
  { fullName: "SELOSE, CLYDE JOSHUA M.", grade: 10 },
  { fullName: "DATOY, JOAQUIN TIMOTHY M.", grade: 9 },
  { fullName: "DELOS ANGELES, EZEKIEL A.", grade: 8 },
  { fullName: "HEBREO, MARQUISE JOAQUIN U.", grade: 10 },
  { fullName: "HILADO, DENZEL HUGHAN B.", grade: 10 },
  { fullName: "HILADO, AIMEE CHARLIZE B.", grade: 12 },
  { fullName: "SUN, KIAN KLARA A.", grade: 10 },
  { fullName: "BANDERADA, GIE ANN SAICY S.", grade: 12 },
  { fullName: "COMETA, THIRDY EXEQUIEL L.", grade: 11 },
  { fullName: "OGUAN, MARIEL O.", grade: 11 },
  { fullName: "DADULA, THEODORE EULYSIS P.", grade: 9 },
  { fullName: "DADULA, ROME ANTHONY P.", grade: 10 },
  { fullName: "TORRES, AZRIEL JAYVER N.", grade: 8 },
  { fullName: "AÑOSA, ALNETTE LEIZYN A.", grade: 8 },
  { fullName: "CAPANANG, ANNA PRINCESS LORRAGNE Y.", grade: 11 },
  { fullName: "MANAHAN, JUSTINE MAURICE B.", grade: 12 },
  { fullName: "MERCADO, MONICA ALLIYAH R.", grade: 7 },
  { fullName: "SUAZO, ZHEA EUNICE M.", grade: 8 },
  { fullName: "BANTASAN, ANGEL B.", grade: 9 }
];

async function main() {
  console.log('Starting seed...');
  
  for (const student of students) {
    await prisma.student.create({
      data: student
    });
  }
  
  console.log(`Seeded ${students.length} students`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
